### ISSUE TITLE
epoll::wait doesn't match the argument order of epoll_wait

### ISSUE THREAD

**Issue by jsancio** [nathansizemore/epoll#10]
Have you consider changing the argument order for `epoll::wait` to match the order used by Linux's `epoll_wait`? User familiar with Linux's epoll API would find the signature more natural if `epoll::wait` had the same order.

I propose the following signature:
```rust
pub fn wait(epfd: RawFd, events: &mut [Event], timeout: i32) -> io::Result<usize>
```

**Comment by nathansizemore** [comment]
You're definitely right. Unfortunately, that would require a new major version to be published and I'd like to only do that when epoll itself has new changes. I've definitely made too many major version bumps as it is and wanna keep those from happening as often. 

But, the next time one is warranted I will definitely add this in!

**Comment by jsancio** [comment]
Thanks for the reply. Your plan sounds good to me.
