### ISSUE TITLE
Incorrect bitflags dependency

### ISSUE THREAD

**Issue by VictorKoenders** [nathansizemore/epoll#14]
epoll depends on bitflags 1.0, but the latest 4.3.0 release depends on a function `from_bits_unchecked` which is only implemented in bitflags 1.2.
This gives issues when upgrading if the project that uses epoll also uses bitflags 1.0. The fix should be to require bitflags 1.2

**Comment by VictorKoenders** [comment]
Dependabot tried updating my epoll 4.3 dependency but left bitflags at 1.1: https://github.com/Trangar/task_manager/pull/4/checks?check_run_id=802679842

Updating bitflags (which was not in my dependency list) to 1.2 with `cargo update` fixed the issue: https://github.com/Trangar/task_manager/pull/4/commits/b275831d0c674ab5b0cd13501be4e01f42be5f43

**Comment by MMunier** [comment]
I made that pull request so its my fault ...
Unfortunately I didn't notice that since cargo had bitflags 1.2.1 in its cache.
