### ISSUE TITLE
ControlOptions should be op code, not flags

### ISSUE THREAD

**Issue by ncarter100** [nathansizemore/epoll#7]
bitflags! {
    pub struct ControlOptions: i32 {
        /// Indicates an addition to the interest list.
        const EPOLL_CTL_ADD = libc::EPOLL_CTL_ADD;
        /// Indicates a modification of flags for an interest already in list.
        const EPOLL_CTL_MOD = libc::EPOLL_CTL_MOD;
        /// Indicates a removal of an interest from the list.
        const EPOLL_CTL_DEL = libc::EPOLL_CTL_DEL;
    }
}
✔  libc [master ✔] $ grep EPOLL_CTL src/unix/notbsd/mod.rs
pub const EPOLL_CTL_ADD: ::c_int = 1;
pub const EPOLL_CTL_MOD: ::c_int = 3;
pub const EPOLL_CTL_DEL: ::c_int = 2;

**Comment by nathansizemore** [comment]
Are you suggesting changing the API to just using regular ints, or an enum? Also, what would be the benefit from changing it?

**Comment by ncarter100** [comment]
I would just remove the bitflags! macro from ControlOptions and the api can be EPOLL_CTL_ADD etc
At the moment if you set EPOLL_CTL_MOD (0x3 => 0b11),  it means you are also silently setting EPOLL_CTL_ADD(0b01) and EPOLL_CTL_DEL(0b10).

**Comment by nathansizemore** [comment]
Not sure it is possible to keep those as a typed struct without the associated types feature, which isn't available in stable yet. Converting to an enum with assigned values is the closest thing I can think of to restrict the input to known good values:

```
pub enum ControlOptions {
    /// Indicates an addition to the interest list.
    EPOLL_CTL_ADD = libc::EPOLL_CTL_ADD as isize,
    /// Indicates a modification of flags for an interest already in list.
    EPOLL_CTL_MOD = libc::EPOLL_CTL_MOD as isize,
    /// Indicates a removal of an interest from the list.
    EPOLL_CTL_DEL = libc::EPOLL_CTL_DEL as isize
}
```

**Comment by ncarter100** [comment]
sounds good to me and thanks for publishing the crate, it was useful.
